{% set name = "b2" %}
{% set version = "4.4.1" %}

package:
  name: backblaze-b2
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/b2-{{ version }}.tar.gz
  sha256: cc3595b035e2a3fbc1e8d923288d3bdbd07a633e79f303ca602a3932d5865572

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - b2 = b2._internal.b2v4.__main__:main
    - b2v3 = b2._internal.b2v3.__main__:main
    - b2v4 = b2._internal.b2v4.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - argcomplete >=3.5.2,<4
    - arrow >=1.0.2,<2.0.0
    - b2sdk >=2.9.4,<3
    - docutils >=0.18.1,<0.22
    - phx-class-registry >=4.0,<5
    - rst2ansi ==0.1.5
    - tabulate ==0.9.0
    - tqdm >=4.65.0,<5
    - platformdirs >=3.11.0,<5
    - setuptools >=60,<80

test:
  imports:
    - b2
  commands:
    - pip check
    - b2 --help
    - b2v3 --help
    - b2v4 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Backblaze/B2_Command_Line_Tool
  summary: Command Line Tool for Backblaze B2
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - freundTech
