{% set name = "b2" %}
{% set version = "4.3.0" %}

package:
  name: backblaze-b2
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/b2-{{ version }}.tar.gz
  sha256: e4576f5d6417e8b89fe0391022257661ab4d18dc4cea366c16e6baddc673a988

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - b2 = b2._internal.b2v4.__main__:main
    - b2v3 = b2._internal.b2v3.__main__:main
    - b2v4 = b2._internal.b2v4.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - argcomplete >=2,<4
    - arrow >=1.0.2,<2.0.0
    - b2sdk >=2.6.0,<3
    - docutils >=0.18.1
    - importlib-metadata >=3.3
    - phx-class-registry >=4.0,<5
    - rst2ansi ==0.1.5
    - tabulate ==0.9.0
    - tqdm >=4.65.0,<5
    - platformdirs >=3.11.0,<5
    - setuptools >=60

test:
  imports:
    - b2
  commands:
    - pip check
    - b2 --help
    - b2v3 --help
    - b2v4 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Backblaze/B2_Command_Line_Tool
  summary: Command Line Tool for Backblaze B2
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - freundTech
