schema_version: 1

context:
  name: b2
  version: "5.0.0"

package:
  name: backblaze-b2
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/b2-${{ version }}.tar.gz
  sha256: dd347f15e0a2c8ea32e1bd5e1a49e294d3ab96b8008051c4e60d1f1505128fe9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - b2 = b2._internal.b2v4.__main__:main
      - b2v3 = b2._internal.b2v3.__main__:main
      - b2v4 = b2._internal.b2v4.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.24.2
    - hatch-vcs >=0.4
    - pip
  run:
    - python >=${{ python_min }}
    - argcomplete >=3.5.2,<4
    - arrow >=1.0.2,<2.0.0
    - b2sdk >=2.12.0,<3
    - docutils >=0.18.1,<0.22
    - rst2ansi ==0.1.5
    - tabulate ==0.9.0
    - tqdm >=4.65.0,<5
    - platformdirs >=3.11.0,<5
  extras:
    full:
      - pydantic >=2.0.1,<3
    license:
      - pip >=26.1
      - pip-licenses 5.0.*
      - pipdeptree >=2.9,<3
      - prettytable 3.9.*

tests:
  - python:
      imports:
        - b2
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - b2 --help
      - b2v3 --help
      - b2v4 --help

about:
  summary: Command Line Tool for Backblaze B2
  license: MIT
  license_file:
    - LICENSE
  homepage: https://github.com/Backblaze/B2_Command_Line_Tool

extra:
  recipe-maintainers:
    - freundTech
